/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "device_gpio.h"
#include "device_rcc.h"
#include "gpio_hal.h"
#include <stdint.h>

void delay(unsigned long);

int main(void)
{

    p_gpio_hal_t gpio_handle = gpio_hal_create(GPIOA_PORT);
    gpio_handle->init(gpio_handle);

    for (;;)
    {
        gpio_handle->toggle(gpio_handle, 5);
        delay(1000000);
        gpio_handle->set(gpio_handle, 5, false);
        delay(1000000);
    }
}

void delay(unsigned long count)
{
    unsigned long i = 0;
    for (i = 0; i < count; i++)
        ;
}