/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "rcc.h"
#include "gpio.h"

int main(void)
{
    p_rcc->ahb1enr |= (1U << RCC_AHB1ENR_GPIOAEN_BIT);  /* Enable GPIOA clock */

    //RCC->AHB1ENR |= GPIOAEN;  /* Enable GPIOA clock */
    /* Loop forever */

    p_gpioa->moder &= ~(3U << (2U * 5U));  // Clear bits 10 and 11
    p_gpioa->moder |=  (1U << (2U * 5U));  // Set bit 10 to make PA5 output
	//GPIOA->MODER &=~(1U<<11);  // make sure bit 11 is off
	//GPIOA->MODER |= (1U<<10);  // set bit 10 on


	for(;;)
    {
        p_gpioa->odr ^= (1U << 5U);  // Toggle PA5
        //GPIOA->ODR ^= (1U<<5);  // Toggle PA5
        for (volatile int i = 0; i < 100000; i++);  // Simple delay
    }
}
