/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "clock_hal.h"
#include "device_gpio.h"
#include "device_rcc.h"
#include "drv_button.h"
#include "drv_led.h"
#include "gpio_hal.h"
#include <stddef.h>
#include <stdint.h>

static p_led_handle_t led_handle = NULL;

void button_callback(button_state_t button_state)
{

    if (button_state == BUTTON_PRESSED)
    {
        drv_led_toggle(led_handle);
    }
}

int main(void)
{
    clock_hal_init();
#if HW_CONFIG_GPIO == 1 && USE_LED_GPIO == 1
    led_handle = drv_led_create(LED_PORT, LED_PIN);
    if (led_handle != NULL)
    {
        drv_led_init(led_handle);
    }
#endif // HW_CONFIG_GPIO AND USE_LED_GPIO

#if HW_CONFIG_GPIO == 1 && USE_BUTTON_GPIO == 1

    p_button_handle_t p_button_handle = drv_button_create(BUTTON_PORT, BUTTON_PIN, button_callback);
    if (p_button_handle != NULL)
    {
        drv_button_init(p_button_handle);
    }
#endif // HW_CONFIG_GPIO AND USE_BUTTON_GPIO

    for (;;)
    {
#if HW_CONFIG_GPIO == 1 && USE_LED_GPIO == 1 && USE_BUTTON_GPIO == 1
        // If GPIO or LED or BUTTON not enabled, just loop
        /*bool button_state = drv_button_is_pressed(p_button_handle);
        if (button_state)
        {
            gpio_hal_set_state(gpiob_handle, LED_PIN, true);
        }
        else
        {
            gpio_hal_set_state(gpiob_handle, LED_PIN, false);
        }
            */

#endif // HW_CONFIG_GPIO AND USE_LED_GPIO AND USE_BUTTON_GPIO
        clock_hal_delay(1000U);
        drv_led_toggle(led_handle);
    }
}
