/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "device_gpio.h"
#include "device_rcc.h"
#include "gpio_hal.h"
#include <stdint.h>
#include <stddef.h>

void delay(unsigned long);

int main(void)
{

    p_gpio_hal_t gpiob_handle = gpio_hal_create(GPIOB_PORT);
    if (gpiob_handle != NULL)
    {
        gpiob_handle->init(gpiob_handle);
        gpiob_handle->direction(gpiob_handle, 13, OUTPUT);
    }
    
    p_gpio_hal_t gpioc_handle = gpio_hal_create(GPIOC_PORT);
    if (gpioc_handle != NULL)
    {
        gpioc_handle->init(gpioc_handle);
        gpioc_handle->direction(gpioc_handle, 13, INPUT);
    }
    

    for (;;)
    {   
        if (gpioc_handle->get(gpioc_handle, 13))
        {
            gpiob_handle->set(gpiob_handle, 13, true);
        }
        else
        //delay(100000); 
        {
            gpiob_handle->set(gpiob_handle, 13, false);
        }
        delay(100000);
    }
}

void delay(unsigned long count)
{
    unsigned long i = 0;
    for (i = 0; i < count; i++)
        ;
}
