/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "device_gpio.h"
#include "device_rcc.h"
#include "drv_button.h"
#include "gpio_hal.h"
#include <stddef.h>
#include <stdint.h>

void delay(unsigned long);

int main(void)
{

#if HW_CONFIG_GPIO == 1 && USE_LED_GPIO == 1
    p_gpio_hal_t gpioa_handle = gpio_hal_create(GPIOA_PORT);
    if (gpioa_handle != NULL)
    {
        gpio_hal_init(gpioa_handle);
        gpio_hal_pin_direction(gpioa_handle, LED_PIN, OUTPUT);
    }
#endif // HW_CONFIG_GPIO AND USE_LED_GPIO

#if HW_CONFIG_GPIO == 1 && USE_BUTTON_GPIO == 1
    //    p_gpio_hal_t gpioc_handle = gpio_hal_create(GPIOC_PORT);
    //    if (gpioc_handle != NULL)
    //    {
    //        gpio_hal_init(gpioc_handle);
    //        gpio_hal_pin_direction(gpioc_handle, BUTTON_PIN, INPUT);
    //    }
    p_button_handle_t p_button_handle = drv_button_create(BUTTON_PORT, BUTTON_PIN, NULL);
    if (p_button_handle != NULL)
    {
        drv_button_init(p_button_handle);
    }
#endif // HW_CONFIG_GPIO AND USE_BUTTON_GPIO

    for (;;)
    {
#if HW_CONFIG_GPIO == 1 && USE_LED_GPIO == 1 && USE_BUTTON_GPIO == 1
        // If GPIO or LED or BUTTON not enabled, just loop
        bool button_state = drv_button_is_pressed(p_button_handle);
        if (button_state)
        // if (gpio_hal_get_state(gpioc_handle, BUTTON_PIN))
        {
            gpio_hal_set_state(gpioa_handle, LED_PIN, true);
        }
        else
        {
            gpio_hal_set_state(gpioa_handle, LED_PIN, false);
        }
#endif // HW_CONFIG_GPIO AND USE_LED_GPIO AND USE_BUTTON_GPIO
        delay(100000);
    }
}

void delay(unsigned long count)
{
    unsigned long i = 0;
    for (i = 0; i < count; i++)
        ;
}